webapp/Areas/CPC/Controllers/SortedCashController.cs
using BaseApp.Entity;
using BaseApp.System;
using CPC;
using CPC.Model;
using ImageResizer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Areas.CPC.Controllers
{
    [AppAuthorize(AppPermission.All, AppPermission.ViewCPC, AppPermission.CPC)]
    public class SortedCashController : AppController
    {
        private SortedCashEntity sortedCashRepo;
        private VaultConsolidatedEntity vaultConsolidatedRepo;
        private EmployeeEntity employeeRepo;
        private BranchEntity branchRepo;
        private Common commonRepo;

        public SortedCashController()
        {
            sortedCashRepo = new SortedCashEntity();
            vaultConsolidatedRepo = new VaultConsolidatedEntity();
            employeeRepo = new EmployeeEntity();
            branchRepo = new BranchEntity();
            commonRepo = new Common();
        }
        public ActionResult SortedCashs()
        {
            return View();
        }
        public PartialViewResult _AllSortedCashs()
        {
            var model = sortedCashRepo.GetAll();
            return PartialView(model);
        }

        #region Details

        public ActionResult Details(Guid Id)
        {
            var model = sortedCashRepo.GetByIdVew(Id);
            //ViewBag.Employees = employeeRepo.GetAll();
            //ViewBag.DenominationList = commonRepo.GetAllDenomination();
            //var branchInfo = branchRepo.GetById(model.ProjectBranchId);
            //ViewData["BranchName"] = $"{branchInfo.BranchCode} - {branchInfo.BranchName}";
            return View(model);
        }
        #endregion
        #region Record
        public ActionResult Record(Guid? Id)
        {
            var model = new CPCSortedCash();
            if (Id.HasValue)
            {
                model = sortedCashRepo.GetById(Id.Value);
            }
            else
            {
                model.ConsignmentNumber = sortedCashRepo.GetNextConsignmentNumber();
                model.Date = DateTime.Now;
                //model.IsActive = true;
            }
            //ViewBag.EmployeeList = new SelectList(employeeRepo.GetDropdown(), "Value", "Text");
            ViewBag.BrachList = new SelectList(branchRepo.GetDropdown(), "Value", "Text");
            //ViewBag.DenominationList = new SelectList(commonRepo.GetAllDenominationDropdown(), "Value", "Text");
            ViewBag.EmployeeList = new SelectList(employeeRepo.GetDropdown(), "Value", "Text");
            ViewBag.DenominationList = commonRepo.GetAllDenomination();
            return View(model);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Record(CPCSortedCash model, List<CPCSortedCashDetail> CPCSortedCashDetail, string Date)
        {
            try
            {
                if (model.Id.IsEmpty())
                {
                    model.CreatedBy = CurrentUser.Id;
                    model.CreatedOn = DateTime.Now;
                    model.IsActive = true;
                    model.Status = (int)AnnexureStatus.Inprocess;
                    model.Date = Utils.SetDateFormate(Date);
                    model.Id = Guid.NewGuid();

                    var lsToSave = model.CPCSortedCashDetails.Where(x => (x.NumberOfPiecesReIssuable > 0 || x.NumberOfPiecesSoiled > 0 || x.NumberOfPiecesMachineRejected > 0 ||
                        x.NumberOfPiecesCounterFeit > 0 || x.NumberOfPiecesMismatch > 0) || (x.NumberOfPiecesClaim > 0) || (x.NumberOfPiecesDesecrated > 0)
                         || (x.NumberOfPiecesShort > 0) || (x.NumberOfPiecesExcess > 0) || (x.NumberOfPiecesUnprocess > 0)).ToList();

                    lsToSave.ForEach(x => { x.Id = Guid.NewGuid(); x.SortedCashId = model.Id; x.CreatedOn = DateTime.Now; x.CreatedBy = CurrentUser.Id; });
                    #region Save Details
                    var res = sortedCashRepo.Create(model);
                    //sortedCashRepo.Create(lsToSave);
                    #endregion
                    if (res.HasValue)
                    {
                        vaultConsolidatedRepo.ChangeStatus(model.DenominationId, model.OrderBookingId, CurrentUser.Id, model.ProjectBranchId);
                        model.Id = res.Value;
                    }

                    #region Activity Log
                    //appLog.Create(CurrentUser.OfficeId, model.Id, CurrentUser.Id, AppLogType.Activity, "CRM - Lead", model.FullName + " lead created", "~/CRM/Contact/LeadRecord > HttpPost", "<table class='table table-hover table-striped table-condensed' style='margin-bottom:15px;'><tr><th class='text-center'>Description</th></tr><tr><td><strong>" + model.FullName + "</strong> lead created by <strong>" + CurrentUser.FullName + "</strong>.</td></tr></table>");
                    #endregion

                    #region EmailSending

                    //Emailer.Send(model.Email, EmailTemplateType.ContactSignup, model);

                    //var appMessageModel = new AppMessage();
                    //appMessageModel.Email = model.Email;
                    //appMessageModel.Status = AppMessageStatus.Outbox;
                    //appMessageModel.Subject = EmailTemplateType.ContactSignup;
                    //appMessageModel.Message = EmailTemplateType.ContactSignup;
                    //TempData["SuccessMsg"] = "Message has been sent successfully.";
                    //realtime.UpdateMessages(null);
                    //appMessageModel.CreatorId = appMessageModel.ContactId = CurrentUser.Id;
                    //appMessageModel.Id = appMsg.Create(appMessageModel);

                    ////var cntact = appUser.GetUserById(new Guid(x));
                    //appMsg.Create(null, appMessageModel.Id, appMessageModel.CreatorId, null, AppMessageStatus.Inbox, EmailTemplateType.ContactSignup, model.Id, null);

                    //realtime.UpdateMessages(null);
                    #endregion

                    TempData["SuccessMsg"] = model.ConsignmentNumber + " has been created successfully.";
                }
                else
                {
                    //model.UpdatedBy = CurrentUser.Id;
                    //model.UpdatedOn = DateTime.Now;
                    //bool res = annexureIIRepo.Update(model);


                    //if (res)
                    //{
                    //    TempData["SuccessMsg"] = model.SrNo + " has been updated successfully.";
                    //}
                    //else
                    //{
                    //    TempData["ErrorMsg"] = "We have encountered an error while processing your request, Please see log for details.";
                    //}
                    #region Activity Log
                    //appLog.Create(CurrentUser.OfficeId, model.Id, CurrentUser.Id, AppLogType.Activity, "CRM - Lead", model.FullName + " lead updated", "~/CRM/Contact/LeadRecord > HttpPost", "<table class='table table-hover table-striped table-condensed' style='margin-bottom:15px;'><tr><th class='text-center'>Description</th></tr><tr><td><strong>" + model.FullName + "</strong> lead updated by <strong>" + CurrentUser.FullName + "</strong>.</td></tr></table>");
                    #endregion

                }
            }
            catch (Exception ex)
            {
                #region Error Log
                //appLog.Create(CurrentUser.OfficeId, null, CurrentUser.Id, AppLogType.Error, "CRM - Lead", ex.GetType().Name.ToSpacedTitleCase(), "~/CMS/FileManager/Index > HttpPost", "<table class='table table-hover table-striped'><tr><th class='text-right'>Source</th><td>" + ex.Source + "</td></tr><tr><th class='text-right'>URL</th><td>" + Request.Url.ToString() + "</td></tr><tr><th class='text-right'>Message</th><td>" + ex.Message + "</td></tr></table><table class='table table-hover table-striped table-condensed'><tr><th class='text-center'>Inner Exception</th></tr><tr><td>" + ex.InnerException + "</td></tr><tr><th class='text-center'>Stack Trace</th></tr><tr><td>" + ex.StackTrace.ToString() + "</td></tr></table>");
                #endregion

                TempData["ErrorMsg"] = "We have encountered an error while processing your request, Please see log for details.";
            }
            //if (SaveClick == "SaveAddNew")
            //{
            //    return RedirectToAction("Record");
            //}
            //else
            //{
            return RedirectToAction("SortedCashs");
        }
        #endregion

        #region Remote Functions

        //[HttpPost]
        //public JsonResult GetCentersByRegionId(Guid Id)
        //{
        //    return Json("");//centerRepo.GetCentersDropdown(Id));
        //}
        //[HttpPost]
        //public JsonResult GetDesignationsByDepartId(Guid Id)
        //{
        //    return Json("");//designationRepo.GetDesignationDropdown(Id));
        //}
        #endregion

        #region Delete
        [HttpPost]
        public JsonResult Delete(Guid Id)
        {
            try
            {
                #region Activity Log
                //appLog.Create(CurrentUser.OfficeId, Id, CurrentUser.Id, AppLogType.Activity, "CRM", "Contact Deleted", "~/CRM/Contact/Delete > HttpPost", "<table class='table table-hover table-striped table-condensed' style='margin-bottom:15px;'><tr><th class='text-center'>Description</th></tr><tr><td>Contact deleted by <strong>" + CurrentUser.FullName + "</strong>.</td></tr></table>");
                #endregion
                sortedCashRepo.InActiveRecord(Id);

                TempData["SuccessMsg"] = "Department has been deleted successfully.";
            }
            catch (Exception ex)
            {
                #region Error Log

webapp/Areas/CPC/Views/SortedCash/Details.cshtml
@model List<Vew_SortedCash>
@{
    ViewBag.Title = "Details";
}


<form id="lead-frm" class="user-Profile" method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-sm-12 text-right">
            <div class="btn-group" role="group">
                <a href="javascript://" onclick="window.history.back()" class="btn btn-default"><i class="fa fa-close"></i> Cancel / Back</a>
                <button type="submit" id="submit" class="btn btn-success"><i class="fa fa-check"></i> Submit</button>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h4> Sorted Cash </h4>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="row form-group">
                                        <label class="col-sm-4 text-left horizontal-label">Order Number</label>
                                        <div class="col-sm-8">
                                            <label class="label label-primary">@Model.FirstOrDefault().OrderNumber</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="row form-group">
                                        <label class="col-sm-4 text-left horizontal-label">Serial Number</label>
                                        <div class="col-sm-8">
                                            <label class="label label-primary">@Model.FirstOrDefault().SealNumber</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="row form-group">
                                        <label class="col-sm-3 horizontal-label">Date</label>
                                        <div class="col-sm-9">
                                            <label class="label label-primary">@Model.FirstOrDefault().Date.ToShortDateString()</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="row form-group">
                                        <label class="col-sm-4 text-left horizontal-label">Denomination</label>
                                        <div class="col-sm-8">
                                            <label class="label label-primary">@Model.FirstOrDefault().DenominationTitle</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="row form-group">
                                        <label class="col-sm-4 text-left horizontal-label">Client/Branch</label>
                                        <div class="col-sm-8">
                                            <label class="label label-primary">@Model.FirstOrDefault().BranchName</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="row form-group">
                                        <label class="col-sm-4 text-left horizontal-label">SealNumber</label>
                                        <div class="col-sm-8">
                                            <label class="label label-primary">@Model.FirstOrDefault().SealNumber</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="row form-group">
                                        <label class="col-sm-4 text-left horizontal-label">City</label>
                                        <div class="col-sm-8">
                                            <label class="label label-primary">@Model.FirstOrDefault().CityName</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="row form-group">
                                        <label class="col-sm-4 text-left horizontal-label">Total Bundles</label>
                                        <div class="col-sm-8">
                                            <label class="label label-primary">@Model.FirstOrDefault().TotalNumberBundles</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="row form-group">
                                        <label class="col-sm-4 text-left horizontal-label">Total Balance</label>
                                        <div class="col-sm-8">
                                            <label class="label label-primary">@Model.FirstOrDefault().TotalBalance</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row tb-padding">
                        <table id="mytableUnsorted" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        Sorter Name
                                    </th>
                                    <th>
                                        Assigned Amount
                                    </th>
                                    <th>
                                        Re-issuable
                                    </th>
                                    <th>
                                        Soiled
                                    </th>
                                    <th>
                                        Machine Rejected
                                    </th>
                                    <th>
                                        CounterFiet
                                    </th>
                                    <th>
                                        Mismatch
                                    </th>
                                    <th>
                                        Claim
                                    </th>
                                    <th>
                                        Desecrated
                                    </th>
                                    <th>
                                        Short
                                    </th>
                                    <th>
                                        Excess
                                    </th>
                                    <th>
                                        Unprocess
                                    </th>
                                    <th>
                                        Amount
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td>
                                        @item.AssignedAmount
                                    </td>
                                    <td>
                                        @(item.NumberOfPiecesReIssuable != null ? item.NumberOfPiecesReIssuable : 0)
                                    </td>
                                    <td>
                                        @(item.NumberOfPiecesSoiled != null ? item.NumberOfPiecesSoiled : 0)
                                    </td>
                                    <td>
                                        @(item.NumberOfPiecesMachineRejected != null ? item.NumberOfPiecesMachineRejected : 0)
                                    </td>
                                    <td>
                                        @(item.NumberOfPiecesCounterFeit != null ? item.NumberOfPiecesCounterFeit : 0)
                                    </td>
                                    <td>
                                        @(item.NumberOfPiecesMismatch != null ? item.NumberOfPiecesMismatch : 0)
                                    </td>
                                    <td>
                                        @(item.NumberOfPiecesClaim != null ? item.NumberOfPiecesClaim : 0)
                                    </td>
                                    <td>
                                        @(item.NumberOfPiecesDesecrated != null ? item.NumberOfPiecesDesecrated : 0)
                                    </td>
                                    <td>
                                        @(item.NumberOfPiecesShort != null ? item.NumberOfPiecesShort : 0)
                                    </td>
                                    <td>
                                        @(item.NumberOfPiecesExcess != null ? item.NumberOfPiecesExcess : 0)
                                    </td>
                                    <td>
                                        @(item.NumberOfPiecesUnprocess != null ? item.NumberOfPiecesUnprocess : 0)
                                    </td>
                                    <td>
                                        @(item.TotalValue != null ? item.TotalValue : 0)
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 text-right">
            <div class="btn-group" role="group">
                <a href="javascript://" onclick="window.history.back()" class="btn btn-default"><i class="fa fa-close"></i> Cancel / Back</a>
                <button type="submit" id="submit" class="btn btn-success"><i class="fa fa-check"></i> Submit</button>
            </div>
        </div>
    </div>
</form>

webapp/Areas/CPC/Views/SortedCash/SortedCashs.cshtml
@{
    ViewBag.Title = "Sorted Cash";
}

<div class="user-Profile" style="min-height:430px;">
    <div id="employees-Container">
        @{ Html.RenderAction("_AllSortedCashs", "SortedCash"); }
    </div>
</div>

@section scripts{
    <script>
        $(function () {
            filterDataTable("#SortedCash-dataTable", [1, 2, 3, 4], [0, 5],10);
        });
    </script>
}

webapp/Areas/CPC/Views/SortedCash/_AllSortedCashs.cshtml
@model List<CPCSortedCash>

<style>
    .menu-links a:hover {
        text-decoration: none;
    }
</style>

<div class="form-Modal">
    <div class="modal-content bg-transparent">
        <div class="modal-header">
            <h3 class="modal-title">
                Sorted Cash Management
                <span class="pull-right menu-links">
                    <a href="javascript://" class="text-muted" title="go to previous" style="margin:0 8px;" onclick="window.history.back()">
                        <i class="fa fa-angle-left"></i> <span class="grid-buttons"> Go Back</span>
                    </a>
                    <a href="javascript://" class="text-danger forceRedirect" title="delete record" style="margin:0 8px;" onclick="deleteMultipleRecords('@Url.Action("DeleteMultiple")', '.checkIt')">
                        <i class="fa fa-trash"></i>
                    </a>
                    <a href="@Url.Action("Record","SortedCash")" style="margin:0 8px;" title="add new">
                        <i class="fa fa-plus-circle text-primary"></i> <span class="grid-buttons"> Add New Sorted Cash</span>
                    </a>
                </span>
            </h3>
        </div>
        <div class="row" style="margin:15px 0">
            <div class="col-md-12">
                <ul class="nav nav-pills">
                    <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-hdd-o"></i> &nbsp; All</a></li>
                    <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-user"></i> &nbsp; Active</a></li>
                    <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-adjust"></i> &nbsp; Invited</a></li>
                    <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-user-times"></i> &nbsp; Suspended</a></li>
                </ul>
            </div>
        </div>
        <div class="modal-body">
            <div class="table-responsive">
                <table id="SortedCash-dataTable" class="table table-hover table-striped table-condensed">
                    <thead>
                        <tr>
                            <th><input type="checkbox" onchange="checkAll(this, 'checkIt');" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Order No." id="SortedCash-dataTable_0" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Consignment No." id="SortedCash-dataTable_1" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Denomination" id="SortedCash-dataTable_2" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Date" id="SortedCash-dataTable_3" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Client" id="SortedCash-dataTable_4" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Status" id="SortedCash-dataTable_5" /></th>
                            <th class="text-center" width="100px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {
                        <tr>
                            <td>
                                @if (CurrentUser.HasAnyPermission(BaseApp.Entity.AppPermission.All, BaseApp.Entity.AppPermission.CPC))
                                {
                                    <input type="checkbox" class="checkIt" value="@x.Id" />
                                }
                            </td>
                            <td><a href="@Url.Action("Details","SortedCash",new { Id = x.Id })">@x.OrderNumber</a></td>
                            <td>@x.ConsignmentNumber</td>
                            <td>@x.DenominationTitle</td>
                            <td>@x.Date</td>
                            <td> @($"{x.CPCProjectBranch.BranchCode} - {x.CPCProjectBranch.BranchName}")</td>
                            @if (x.Status == 1)
                            {
                                <td> <label class="label label-info">@AnnexureStatus.Inprocess</label></td>
                            }
                            else
                            {
                                <td> <label class="label label-success">@AnnexureStatus.Completed</label></td>
                            }
                            <td class="text-center">
                                <div class="btn-group btn-group-xs" role="group">
                                    @*<a href="@Url.Action("Details","SortedCash")/@x.Id/1" class="btn btn-primary" title="Details">*@
                                    <a href="@Url.Action("Details","SortedCash",new { Id = x.Id })" class="btn btn-primary" title="Details"><i class="fa fa-eye"></i></a>
                                    @if (CurrentUser.HasAnyPermission(BaseApp.Entity.AppPermission.All, BaseApp.Entity.AppPermission.CPC))
                                    {
                                        @*<a href="@Url.Action("Record","SortedCashDetail")/@x.Id" class="btn btn-info" title="Edit"><i class="fa fa-edit"></i></a>*@
                                        <a href="javascript://" onclick="deleteRecord('@Url.Action("Delete")', '@x.Id')" class="btn btn-danger" title="Delete"><i class="fa fa-trash"></i></a>
                                    }
                                </div>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer text-right">
            <div class="pull-right menu-links">
                <a href="javascript://" class="text-muted" title="go to previous" style="margin:0 8px;" onclick="window.history.back()">
                    <i class="fa fa-angle-left fa-2x"></i> <span class="grid-buttons"> Go Back</span>
                </a>
                <a href="javascript://" class="text-danger forceRedirect" title="delete record" style="margin:0 8px;" onclick="deleteMultipleRecords('@Url.Action("DeleteMultiple")', '.checkIt')">
                    <i class="fa fa-trash fa-2x"></i>
                </a>
                <a href="@Url.Action("Record","SortedCash")" style="margin:0 8px;" title="add new">
                    <i class="fa fa-plus-circle fa-2x text-primary"></i> <span class="grid-buttons"> Add New Sorted Cash</span>
                </a>
            </div>
        </div>
    </div>
</div>