webapp/Areas/CPC/Controllers/CashInTransitController.cs
using BaseApp.Entity;
using BaseApp.System;
using CPC;
using CPC.Model;
using ImageResizer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace WebApp.Areas.CPC.Controllers
{
    [AppAuthorize(AppPermission.All, AppPermission.ViewCPC, AppPermission.CPC)]
    public class CashInTransitController : AppController
    {
        private CashInTransitEntity cashInTransitRepo;
        private EmployeeEntity employeeRepo;
        private BranchEntity branchRepo;
        private Common commonRepo;

        public CashInTransitController()
        {
            cashInTransitRepo = new CashInTransitEntity();
            employeeRepo = new EmployeeEntity();
            branchRepo = new BranchEntity();
            commonRepo = new Common();
        }
        public ActionResult CashInTransits()
        {
            return View();
        }
        public PartialViewResult _AllCashInTransits()
        {
            var model = cashInTransitRepo.GetAll();
            return PartialView(model);
        }

        #region Details

        public ActionResult Details(Guid Id)
        {
            var model = cashInTransitRepo.GetById(Id);
            ViewBag.Employees = employeeRepo.GetAll();
            ViewBag.DenominationList = commonRepo.GetAllDenomination();
            return View(model);
        }
        #endregion
        #region Record
        public ActionResult Record(Guid? Id)
        {
            ViewData["IsView"] = Convert.ToString(TempData["IsView"]);
            var model = new CPCCashInTransit();
            if (Id.HasValue)
            {
                model = cashInTransitRepo.GetById(Id.Value);
                model.Date = DateTime.Now;
                model.DeliveryDateTime = DateTime.Now;
                model.CollectionDateTime = DateTime.Now;
            }
            else
            {
                model.ShipmentReceiptNumber = cashInTransitRepo.GetNextShipmentNo();
                //model.IsActive = true;
            }
            //ViewBag.EmployeeList = new SelectList(employeeRepo.GetDropdown(), "Value", "Text");
            ViewBag.BrachList = new SelectList(branchRepo.GetDropdown(), "Value", "Text");
            //ViewBag.DenominationList = new SelectList(commonRepo.GetAllDenominationDropdown(), "Value", "Text");
            ViewBag.EmployeeList = new SelectList(employeeRepo.GetDropdown(), "Value", "Text");
            ViewBag.DenominationList = commonRepo.GetAllDenomination();
            return View(model);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Record(CPCCashInTransit model, List<CPCCashInTransitChild> CPCCashInTransitChild, List<CPCCashInTransitDenomination> CPCCashInTransitDenomination, string Date, string CollectionDateTime, string DeliveryDateTime)
        {
            try
            {
                if (model.Id.IsEmpty())
                {
                    model.CreatedBy = CurrentUser.Id;
                    model.CreatedOn = DateTime.Now;
                    model.IsActive = true;
                    model.Date = Utils.SetDateFormate(Date);
                    model.CollectionDateTime = Utils.SetDateFormate(CollectionDateTime);
                    model.DeliveryDateTime = Utils.SetDateFormate(DeliveryDateTime);
                    model.Id = Guid.NewGuid();
                    var res = cashInTransitRepo.Create(model);
                    if (res.HasValue)
                    {
                        var lsToSave = CPCCashInTransitChild.Where(x => x.SealNumber > 0 && (x.Item != "" || x.Value == 0 || x.PartialDelivery != "")).ToList();
                        lsToSave.ForEach(x => { x.Id = Guid.NewGuid(); x.CashInTransitId = model.Id; x.CreatedOn = DateTime.Now; x.CreatedBy = CurrentUser.Id; });
                        #region Save Details
                        cashInTransitRepo.Create(lsToSave);
                        #endregion

                        var lsToSaveDenom = CPCCashInTransitDenomination.Where(y => y.NumberOfPackets != 0 && (y.TotalValue != 0)).ToList();
                        lsToSaveDenom.ForEach(y => { y.Id = Guid.NewGuid(); y.CashInTransitId = model.Id; y.CreatedOn = DateTime.Now; y.CreatedBy = CurrentUser.Id; });
                        #region Save Details
                        cashInTransitRepo.Create(lsToSaveDenom);
                        #endregion

                        model.Id = res.Value;
                    }

                    #region Activity Log
                    //appLog.Create(CurrentUser.OfficeId, model.Id, CurrentUser.Id, AppLogType.Activity, "CRM - Lead", model.FullName + " lead created", "~/CRM/Contact/LeadRecord > HttpPost", "<table class='table table-hover table-striped table-condensed' style='margin-bottom:15px;'><tr><th class='text-center'>Description</th></tr><tr><td><strong>" + model.FullName + "</strong> lead created by <strong>" + CurrentUser.FullName + "</strong>.</td></tr></table>");
                    #endregion

                    #region EmailSending

                    //Emailer.Send(model.Email, EmailTemplateType.ContactSignup, model);

                    //var appMessageModel = new AppMessage();
                    //appMessageModel.Email = model.Email;
                    //appMessageModel.Status = AppMessageStatus.Outbox;
                    //appMessageModel.Subject = EmailTemplateType.ContactSignup;
                    //appMessageModel.Message = EmailTemplateType.ContactSignup;
                    //TempData["SuccessMsg"] = "Message has been sent successfully.";
                    //realtime.UpdateMessages(null);
                    //appMessageModel.CreatorId = appMessageModel.ContactId = CurrentUser.Id;
                    //appMessageModel.Id = appMsg.Create(appMessageModel);

                    ////var cntact = appUser.GetUserById(new Guid(x));
                    //appMsg.Create(null, appMessageModel.Id, appMessageModel.CreatorId, null, AppMessageStatus.Inbox, EmailTemplateType.ContactSignup, model.Id, null);

                    //realtime.UpdateMessages(null);
                    #endregion

                    TempData["SuccessMsg"] = model.ShipmentReceiptNumber + " has been created successfully.";
                }
                else
                {
                    //model.UpdatedBy = CurrentUser.Id;
                    //model.UpdatedOn = DateTime.Now;
                    //bool res = annexureIIRepo.Update(model);


                    //if (res)
                    //{
                    //    TempData["SuccessMsg"] = model.SrNo + " has been updated successfully.";
                    //}
                    //else
                    //{
                    //    TempData["ErrorMsg"] = "We have encountered an error while processing your request, Please see log for details.";
                    //}
                    #region Activity Log
                    //appLog.Create(CurrentUser.OfficeId, model.Id, CurrentUser.Id, AppLogType.Activity, "CRM - Lead", model.FullName + " lead updated", "~/CRM/Contact/LeadRecord > HttpPost", "<table class='table table-hover table-striped table-condensed' style='margin-bottom:15px;'><tr><th class='text-center'>Description</th></tr><tr><td><strong>" + model.FullName + "</strong> lead updated by <strong>" + CurrentUser.FullName + "</strong>.</td></tr></table>");
                    #endregion

                }
            }
            catch (Exception ex)
            {
                #region Error Log
                //appLog.Create(CurrentUser.OfficeId, null, CurrentUser.Id, AppLogType.Error, "CRM - Lead", ex.GetType().Name.ToSpacedTitleCase(), "~/CMS/FileManager/Index > HttpPost", "<table class='table table-hover table-striped'><tr><th class='text-right'>Source</th><td>" + ex.Source + "</td></tr><tr><th class='text-right'>URL</th><td>" + Request.Url.ToString() + "</td></tr><tr><th class='text-right'>Message</th><td>" + ex.Message + "</td></tr></table><table class='table table-hover table-striped table-condensed'><tr><th class='text-center'>Inner Exception</th></tr><tr><td>" + ex.InnerException + "</td></tr><tr><th class='text-center'>Stack Trace</th></tr><tr><td>" + ex.StackTrace.ToString() + "</td></tr></table>");
                #endregion

                TempData["ErrorMsg"] = "We have encountered an error while processing your request, Please see log for details.";
            }
            //if (SaveClick == "SaveAddNew")
            //{
            //    return RedirectToAction("Record");
            //}
            //else
            //{
            return RedirectToAction("CashInTransits");
        }
        #endregion

        #region Remote Functions

        //[HttpPost]
        //public JsonResult GetCentersByRegionId(Guid Id)
        //{
        //    return Json("");//centerRepo.GetCentersDropdown(Id));
        //}
        //[HttpPost]
        //public JsonResult GetDesignationsByDepartId(Guid Id)
        //{
        //    return Json("");//designationRepo.GetDesignationDropdown(Id));
        //}
        #endregion

        #region Delete
        [HttpPost]
        public JsonResult Delete(Guid Id)
        {
            try
            {
                #region Activity Log
                //appLog.Create(CurrentUser.OfficeId, Id, CurrentUser.Id, AppLogType.Activity, "CRM", "Contact Deleted", "~/CRM/Contact/Delete > HttpPost", "<table class='table table-hover table-striped table-condensed' style='margin-bottom:15px;'><tr><th class='text-center'>Description</th></tr><tr><td>Contact deleted by <strong>" + CurrentUser.FullName + "</strong>.</td></tr></table>");
                #endregion
                cashInTransitRepo.InActiveRecord(Id);

                TempData["SuccessMsg"] = "Department has been deleted successfully.";
            }
            catch (Exception ex)
            {
                #region Error Log

webapp/Areas/CPC/Views/CashInTransit/CashInTransits.cshtml
@{
    ViewBag.Title = "CIT Shipment";
}

<div class="user-Profile" style="min-height:430px;">
    <div id="employees-Container">
        @{ Html.RenderAction("_AllCashInTransits", "CashInTransit"); }
    </div>
</div>

@section scripts{
    <script>
        $(function () {
            filterDataTable("#CashInTransit-dataTable", [1, 2, 3, 4, 5], [0, 6],10);
        });
    </script>
}

webapp/Areas/CPC/Views/CashInTransit/_AllCashInTransits.cshtml
@model List<CPCCashInTransit>

<style>
    .menu-links a:hover {
        text-decoration: none;
    }
</style>

<div class="form-Modal">
    <div class="modal-content bg-transparent">
        <div class="modal-header">
            <h3 class="modal-title">
                CIT Shipment Management
                <span class="pull-right menu-links">
                    <a href="javascript://" class="text-muted" title="go to previous" style="margin:0 8px;" onclick="window.history.back()">
                        <i class="fa fa-angle-left"></i> <span class="grid-buttons"> Go Back</span>
                    </a>
                    <a href="javascript://" class="text-danger forceRedirect" title="delete record" style="margin:0 8px;" onclick="deleteMultipleRecords('@Url.Action("DeleteMultiple")', '.checkIt')">
                        <i class="fa fa-trash"></i>
                    </a>
                    <a href="@Url.Action("Record","CashInTransit")" style="margin:0 8px;" title="add new">
                        <i class="fa fa-plus-circle text-primary"></i> <span class="grid-buttons"> Add New CIT Shipment</span>
                    </a>
                </span>
            </h3>
        </div>
        <div class="row" style="margin:15px 0">
            <div class="col-md-12">
                <ul class="nav nav-pills">
                    <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-hdd-o"></i> &nbsp; All</a></li>
                    <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-user"></i> &nbsp; Active</a></li>
                    <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-adjust"></i> &nbsp; Invited</a></li>
                    <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-user-times"></i> &nbsp; Suspended</a></li>
                </ul>
            </div>
        </div>
        <div class="modal-body">
            <div class="table-responsive">
                <table id="CashInTransit-dataTable" class="table table-hover table-striped table-condensed">
                    <thead>
                        <tr>
                            <th><input type="checkbox" onchange="checkAll(this, 'checkIt');" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Shipment No." id="CashInTransit-dataTable_0" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Customer" id="CashInTransit-dataTable_1" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Vehicle No." id="CashInTransit-dataTable_2" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Updated On" id="CashInTransit-dataTable_3" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Status" id="CashInTransit-dataTable_4" /></th>
                            <th class="text-center" width="100px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {
                        <tr>
                            <td>
                                @if (CurrentUser.HasAnyPermission(BaseApp.Entity.AppPermission.All, BaseApp.Entity.AppPermission.CPC))
                                {
                                    <input type="checkbox" class="checkIt" value="@x.Id" />
                                }
                            </td>
                            <td><a href="@Url.Action("Details","CashInTransit",new { Id = x.Id })">@x.ShipmentReceiptNumber</a></td>
                            <td>@x.CustomerToBeBilled</td>
                            <td>@x.VehicleNumber</td>
                            <td>@x.Date</td>
                            @if (x.Status == 1)
                            {
                            <td> <label class="label label-warning">@AnnexureStatus.Inprocess</label></td>
                            }
                            else
                            {
                            <td> <label class="label label-warning">@AnnexureStatus.Completed</label></td>
                            }
                            <td class="text-center">
                                <div class="btn-group btn-group-xs" role="group">
                                    @*<a href="@Url.Action("Details","CashInTransit")/@x.Id/1" class="btn btn-primary" title="Details">*@
                                    <a href="@Url.Action("Details","CashInTransit",new { Id = x.Id })" class="btn btn-primary" title="Details"><i class="fa fa-eye"></i></a>
                                    @if (CurrentUser.HasAnyPermission(BaseApp.Entity.AppPermission.All, BaseApp.Entity.AppPermission.CPC))
                                    {
                                        @*<a href="@Url.Action("Record","CashInTransit")/@x.Id" class="btn btn-info" title="Edit"><i class="fa fa-edit"></i></a>*@
                                        <a href="javascript://" onclick="deleteRecord('@Url.Action("Delete")', '@x.Id')" class="btn btn-danger" title="Delete"><i class="fa fa-trash"></i></a>
                                    }
                                </div>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer text-right">
            <div class="pull-right menu-links">
                <a href="javascript://" class="text-muted" title="go to previous" style="margin:0 8px;" onclick="window.history.back()">
                    <i class="fa fa-angle-left fa-2x"></i> <span class="grid-buttons"> Go Back</span>
                </a>
                <a href="javascript://" class="text-danger forceRedirect" title="delete record" style="margin:0 8px;" onclick="deleteMultipleRecords('@Url.Action("DeleteMultiple")', '.checkIt')">
                    <i class="fa fa-trash fa-2x"></i>
                </a>
                <a href="@Url.Action("Record","CashInTransit")" style="margin:0 8px;" title="add new">
                    <i class="fa fa-plus-circle fa-2x text-primary"></i> <span class="grid-buttons"> Add New CIT Shipment</span>
                </a>
            </div>
        </div>
    </div>
</div>