webapp/Areas/CPC/Controllers/UnsortedCashController.cs
using BaseApp.Entity;
using BaseApp.System;
using CPC;
using CPC.Model;
using ImageResizer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Areas.CPC.Controllers
{
    [AppAuthorize(AppPermission.All, AppPermission.ViewCPC, AppPermission.CPC, AppPermission.ViewVaultManager, AppPermission.VaultManager)]
    public class UnsortedCashController : AppController
    {
        private UnsortedCashEntity unsortedCashRepo;
        private AnnexureIEntity annexureIrepo;
        private EmployeeEntity employeeRepo;
        private BranchEntity branchRepo;
        private Common commonRepo;

        public UnsortedCashController()
        {
            unsortedCashRepo = new UnsortedCashEntity();
            annexureIrepo = new AnnexureIEntity();
            employeeRepo = new EmployeeEntity();
            branchRepo = new BranchEntity();
            commonRepo = new Common();
        }
        public ActionResult UnsortedCashs()
        {
            return View();
        }
        public PartialViewResult _AllUnsortedCashs()
        {
            var model = unsortedCashRepo.GetAll();
            return PartialView(model);
        }

        #region Details

        public ActionResult Details(Guid Id)
        {
            var model = unsortedCashRepo.GetById(Id);
            ViewBag.Employees = employeeRepo.GetAll();
            ViewBag.DenominationList = commonRepo.GetAllDenomination();
            var branchInfo = branchRepo.GetById(model.ProjectBranchId);
            ViewData["BranchName"] = $"{branchInfo.BranchCode} - {branchInfo.BranchName}";
            return View(model);
        }
        #endregion

        #region Record
        public ActionResult Record(Guid? Id)
        {
            var model = new CPCUnsortedCash();
            if (Id.HasValue)
            {
                model = unsortedCashRepo.GetById(Id.Value);
            }
            else
            {
                model.SerialNumber = unsortedCashRepo.GetNextSerialNumber();
                model.Date = DateTime.Now;
                //model.IsActive = true;
            }
            //ViewBag.EmployeeList = new SelectList(employeeRepo.GetDropdown(), "Value", "Text");
            //ViewBag.DenominationList = new SelectList(commonRepo.GetAllDenominationDropdown(), "Value", "Text");
            ViewBag.EmployeeList = new SelectList(employeeRepo.GetDropdown(), "Value", "Text");
            ViewBag.DenominationList = commonRepo.GetAllDenomination();
            return View(model);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Record(CPCUnsortedCash model, List<CPCUnsortedCashDetail> CPCUnsortedCashDetail, string Date)
        {
            try
            {
                if (model.Id.IsEmpty())
                {
                    model.CreatedBy = CurrentUser.Id;
                    model.CreatedOn = DateTime.Now;
                    model.IsActive = true;
                    model.Status =(int)AnnexureStatus.Inprocess;
                    model.Date = Utils.SetDateFormate(Date);
                    model.Id = Guid.NewGuid();
                    var res = unsortedCashRepo.Create(model);
                    if (res.HasValue)
                    {
                        var lsToSave = CPCUnsortedCashDetail.Where(x => x.NumberOfBundles > 0 && (x.TotalValue != 0)).ToList();
                        lsToSave.ForEach(x => { x.Id = Guid.NewGuid(); x.UnsortedCashId = model.Id; x.CreatedOn = DateTime.Now; x.CreatedBy = CurrentUser.Id; });
                        #region Save Details
                        unsortedCashRepo.Create(lsToSave);
                        #endregion

                        annexureIrepo.ChangeStatus(model.OrderBookingId, CurrentUser.Id, model.ProjectBranchId, AnnexureStatus.Proceeded);
                        //annexureIrepo.ChangeMasterStatus(model.OrderBookingId, CurrentUser.Id);
                        model.Id = res.Value;
                    }

                    #region Activity Log
                    //appLog.Create(CurrentUser.OfficeId, model.Id, CurrentUser.Id, AppLogType.Activity, "CRM - Lead", model.FullName + " lead created", "~/CRM/Contact/LeadRecord > HttpPost", "<table class='table table-hover table-striped table-condensed' style='margin-bottom:15px;'><tr><th class='text-center'>Description</th></tr><tr><td><strong>" + model.FullName + "</strong> lead created by <strong>" + CurrentUser.FullName + "</strong>.</td></tr></table>");
                    #endregion

                    #region EmailSending

                    //Emailer.Send(model.Email, EmailTemplateType.ContactSignup, model);

                    //var appMessageModel = new AppMessage();
                    //appMessageModel.Email = model.Email;
                    //appMessageModel.Status = AppMessageStatus.Outbox;
                    //appMessageModel.Subject = EmailTemplateType.ContactSignup;
                    //appMessageModel.Message = EmailTemplateType.ContactSignup;
                    //TempData["SuccessMsg"] = "Message has been sent successfully.";
                    //realtime.UpdateMessages(null);
                    //appMessageModel.CreatorId = appMessageModel.ContactId = CurrentUser.Id;
                    //appMessageModel.Id = appMsg.Create(appMessageModel);

                    ////var cntact = appUser.GetUserById(new Guid(x));
                    //appMsg.Create(null, appMessageModel.Id, appMessageModel.CreatorId, null, AppMessageStatus.Inbox, EmailTemplateType.ContactSignup, model.Id, null);

                    //realtime.UpdateMessages(null);
                    #endregion

                    TempData["SuccessMsg"] = model.SerialNumber + " has been created successfully.";
                }
                else
                {
                    //model.UpdatedBy = CurrentUser.Id;
                    //model.UpdatedOn = DateTime.Now;
                    //bool res = annexureIIRepo.Update(model);


                    //if (res)
                    //{
                    //    TempData["SuccessMsg"] = model.SrNo + " has been updated successfully.";
                    //}
                    //else
                    //{
                    //    TempData["ErrorMsg"] = "We have encountered an error while processing your request, Please see log for details.";
                    //}
                    #region Activity Log
                    //appLog.Create(CurrentUser.OfficeId, model.Id, CurrentUser.Id, AppLogType.Activity, "CRM - Lead", model.FullName + " lead updated", "~/CRM/Contact/LeadRecord > HttpPost", "<table class='table table-hover table-striped table-condensed' style='margin-bottom:15px;'><tr><th class='text-center'>Description</th></tr><tr><td><strong>" + model.FullName + "</strong> lead updated by <strong>" + CurrentUser.FullName + "</strong>.</td></tr></table>");
                    #endregion

                }
            }
            catch (Exception ex)
            {
                #region Error Log
                //appLog.Create(CurrentUser.OfficeId, null, CurrentUser.Id, AppLogType.Error, "CRM - Lead", ex.GetType().Name.ToSpacedTitleCase(), "~/CMS/FileManager/Index > HttpPost", "<table class='table table-hover table-striped'><tr><th class='text-right'>Source</th><td>" + ex.Source + "</td></tr><tr><th class='text-right'>URL</th><td>" + Request.Url.ToString() + "</td></tr><tr><th class='text-right'>Message</th><td>" + ex.Message + "</td></tr></table><table class='table table-hover table-striped table-condensed'><tr><th class='text-center'>Inner Exception</th></tr><tr><td>" + ex.InnerException + "</td></tr><tr><th class='text-center'>Stack Trace</th></tr><tr><td>" + ex.StackTrace.ToString() + "</td></tr></table>");
                #endregion

                TempData["ErrorMsg"] = "We have encountered an error while processing your request, Please see log for details.";
            }
            //if (SaveClick == "SaveAddNew")
            //{
            //    return RedirectToAction("Record");
            //}
            //else
            //{
            return RedirectToAction("UnsortedCashs");
        }
        #endregion

        #region Annexure Popup
        public ActionResult _UnsortedCashList()
        {
            var model = unsortedCashRepo.GetAllApproved();
            ViewBag.DetailsList = unsortedCashRepo.GetAllDetails();
            return PartialView(model);
        }
        #endregion

        #region Remote Functions
        [HttpGet]
        public JsonResult GetUnsortedCash(Guid id)
        {
            try
            {
                var List = unsortedCashRepo.GetAllDetailsById(id);
                return Json(new
                {
                    List.FirstOrDefault().ProjectBranchId,
                    List.FirstOrDefault().BranchName,
                    List.FirstOrDefault().OrderNumber,
                    List.FirstOrDefault().SerialNumber,
                    List.FirstOrDefault().CityId,
                    List.FirstOrDefault().CityName,
                    List.FirstOrDefault().OrderBookingId,

                    Details = List.Select(x => new {
                        x.DenominationId,
                        x.DenominationTitle,
                        x.NumberOfBundles,
                        x.TotalValue,
                        x.SealNo
                    }).ToList(),

                }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion
        #region
        //[HttpPost]
        //public JsonResult GetCentersByRegionId(Guid Id)
        //{
        //    return Json("");//centerRepo.GetCentersDropdown(Id));
        //}
        //[HttpPost]
        //public JsonResult GetDesignationsByDepartId(Guid Id)
        //{

webapp/Areas/CPC/Views/UnsortedCash/UnsortedCashs.cshtml
@{
    ViewBag.Title = "Unsorted Cash";
}

<div class="user-Profile" style="min-height:430px;">
    <div id="employees-Container">
        @{ Html.RenderAction("_AllUnsortedCashs", "UnsortedCash"); }
    </div>
</div>

@section scripts{
    <script>
        $(function () {
            filterDataTable("#UnsortedCashs-dataTable", [1, 2, 3, 4,5], [0, 6],10);
        });
    </script>
}

webapp/Areas/CPC/Views/UnsortedCash/_AllUnsortedCashs.cshtml
@model List<CPCUnsortedCash>

<style>
    .menu-links a:hover {
        text-decoration: none;
    }
</style>

<div class="form-Modal">
    <div class="modal-content bg-transparent">
        <div class="modal-header">
            <h3 class="modal-title">
                Unsorted Cash Management
                <span class="pull-right menu-links">
                    <a href="javascript://" class="text-muted" title="go to previous" style="margin:0 8px;" onclick="window.history.back()">
                        <i class="fa fa-angle-left"></i> <span class="grid-buttons"> Go Back</span>
                    </a>
                    <a href="javascript://" class="text-danger forceRedirect" title="delete record" style="margin:0 8px;" onclick="deleteMultipleRecords('@Url.Action("DeleteMultiple")', '.checkIt')">
                        <i class="fa fa-trash"></i>
                    </a>
                    <a href="@Url.Action("Record","UnsortedCash")" style="margin:0 8px;" title="add new">
                        <i class="fa fa-plus-circle text-primary"></i> <span class="grid-buttons"> Add New Unsorted Cash</span>
                    </a>
                </span>
            </h3>
        </div>
        @*<div class="row" style="margin:15px 0">
            <div class="col-md-12">
                <ul class="nav nav-pills">
                    <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-hdd-o"></i> &nbsp; All</a></li>
                    <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-user"></i> &nbsp; Active</a></li>
                    <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-adjust"></i> &nbsp; Invited</a></li>
                    <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-user-times"></i> &nbsp; Suspended</a></li>
                </ul>
            </div>
        </div>*@
        <div class="modal-body">
            <div class="table-responsive">
                <table id="UnsortedCashs-dataTable" class="table table-hover table-striped table-condensed">
                    <thead>
                        <tr>
                            <th><input type="checkbox" onchange="checkAll(this, 'checkIt');" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Order No" id="UnsortedCash-dataTable_0" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Consignment No." id="UnsortedCash-dataTable_1" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Date" id="UnsortedCash-dataTable_2" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Client" id="UnsortedCash-dataTable_3" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Status" id="UnsortedCash-dataTable_4" /></th>
                            <th class="text-center" width="100px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {
                        <tr>
                            <td>
                                @if (CurrentUser.HasAnyPermission(BaseApp.Entity.AppPermission.All, BaseApp.Entity.AppPermission.CPC))
                                {
                                    <input type="checkbox" class="checkIt" value="@x.Id" />
                                }
                            </td>
                            <td>@x.OrderNumber</td>
                            <td><a href="@Url.Action("Details","UnsortedCash",new { Id = x.Id })">@x.SerialNumber</a></td>
                            <td>@x.Date</td>
                            <td> @($"{x.CPCProjectBranch.BranchCode} - {x.CPCProjectBranch.BranchName}")</td>
                            @if (x.Status == 1)
                            {
                                <td> <label class="label label-info">@AnnexureStatus.Inprocess</label></td>
                            }
                            else
                            {
                                <td> <label class="label label-success">@AnnexureStatus.Completed</label></td>
                            }
                            <td class="text-center">
                                <div class="btn-group btn-group-xs" role="group">
                                    @*<a href="@Url.Action("Details","UnsortedCash")/@x.Id/1" class="btn btn-primary" title="Details">*@
                                    <a href="@Url.Action("Details","UnsortedCash",new { Id = x.Id })" class="btn btn-primary" title="Details"><i class="fa fa-eye"></i></a>
                                    @if (CurrentUser.HasAnyPermission(BaseApp.Entity.AppPermission.All, BaseApp.Entity.AppPermission.CPC))
                                    {
                                        @*<a href="@Url.Action("Record","UnsortedCashDetail")/@x.Id" class="btn btn-info" title="Edit"><i class="fa fa-edit"></i></a>*@
                                        <a href="javascript://" onclick="deleteRecord('@Url.Action("Delete")', '@x.Id')" class="btn btn-danger" title="Delete"><i class="fa fa-trash"></i></a>
                                    }
                                </div>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer text-right">
            <div class="pull-right menu-links">
                <a href="javascript://" class="text-muted" title="go to previous" style="margin:0 8px;" onclick="window.history.back()">
                    <i class="fa fa-angle-left fa-2x"></i> <span class="grid-buttons"> Go Back</span>
                </a>
                <a href="javascript://" class="text-danger forceRedirect" title="delete record" style="margin:0 8px;" onclick="deleteMultipleRecords('@Url.Action("DeleteMultiple")', '.checkIt')">
                    <i class="fa fa-trash fa-2x"></i>
                </a>
                <a href="@Url.Action("Record","UnsortedCash")" style="margin:0 8px;" title="add new">
                    <i class="fa fa-plus-circle fa-2x text-primary"></i> <span class="grid-buttons"> Add New Unsorted Cash</span>
                </a>
            </div>
        </div>
    </div>
</div>

webapp/Areas/CPC/Views/UnsortedCash/_UnsortedCashList.cshtml
@model List<CPCUnsortedCash>
@{
    var detailsList = ViewBag.DetailsList as List<Vew_UnsortedCash>;
}

<form id="frm" class="form-Modal" method="post" action="~/" enctype="multipart/form-data">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Assigned Unsorted Cash</h4>
        </div>
        <div class="modal-body">
            <div class="table-responsive">
                <table id="UnsortedCash-dataTable" class="table table-hover table-striped table-condensed">
                    <thead>
                        <tr>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Order No" id="AnnexureIBooking-dataTable_0" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Sr No" id="AnnexureIBooking-dataTable_1" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Date" id="AnnexureIBooking-dataTable_2" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="No Of Bundles" id="AnnexureIBooking-dataTable_3" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Total Amount" id="AnnexureIBooking-dataTable_4" /></th>
                            <th><input class="form-control input-sm input-tbl" type="text" placeholder="Status" id="AnnexureIBooking-dataTable_5" /></th>
                            <th class="text-center" width="100px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {
                        <tr>
                            <td>
                                @x.OrderNumber
                            </td>
                            <td>
                                @x.SerialNumber
                            </td>
                            <td>
                                @x.Date.ToString(Constants.DATE_FORMAT_CLIENT_SIDE)
                            </td>

                            <td>@(detailsList.Where(ab => ab.Id == x.Id).ToList() != null ? detailsList.Where(ab => ab.Id == x.Id).Sum(y => y.NumberOfBundles) : 0)</td>
                            <td>@(detailsList.Where(ab => ab.Id == x.Id).ToList() != null ? detailsList.Where(ab => ab.Id == x.Id).Sum(y => y.TotalValue) : 0)</td>
                            <td>
                                @if (x.Status == (int)AnnexureStatus.Approved)
                                {
                                    <label class="label label-success">Approved</label>
                                }
                                else
                                {
                                    <label class="label label-warning">Inprocess</label>
                                }
                            </td>
                            <td class="text-center">
                                <div class="btn-group btn-group-xs" role="group">
                                    <a onclick="getOrderId('@(x.Id)')" href="javascript://" class="btn btn-primary mg-r" title="Details"><i class="fa fa-check fa-2x"></i> </a>
                                </div>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer text-right">
            <div class="btn-group btn-group-sm" role="group">
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Cancel</button>
            </div>
        </div>
    </div>
</form>