webapp/Areas/CPC/Controllers/AnnexureIIIController.cs
using BaseApp.Entity;
using BaseApp.System;
using CPC;
using CPC.Model;
using ImageResizer;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace WebApp.Areas.CPC.Controllers
{
    [AppAuthorize(AppPermission.All, AppPermission.ViewCPC, AppPermission.CPC)]
    public class AnnexureIIIController : AppController
    {
        private AnnexureIIIEntity annexureIIIRepo;
        private EmployeeEntity employeeRepo;
        private BranchEntity branchRepo;
        private Common commonRepo;

        public AnnexureIIIController()
        {
            annexureIIIRepo = new AnnexureIIIEntity();
            employeeRepo = new EmployeeEntity();
            branchRepo = new BranchEntity();
            commonRepo = new Common();
        }
        public ActionResult AnnexureIIIs()
        {
            return View();
        }
        public PartialViewResult _AllAnnexureIII()
        {
            var model = annexureIIIRepo.GetAll();
            ViewBag.Employees = employeeRepo.GetAll();
            return PartialView(model);
        }

        #region Details
        public ActionResult Details(Guid Id)
        {
            var model = annexureIIIRepo.GetById(Id);
            //model.CPCAnnexureIIIDetails = annexureIIIRepo.GetDetailsByMasterId(Id);
            ViewBag.Employees = employeeRepo.GetAll();
            var branchInfo = branchRepo.GetById(model.CashCollectedFromId.Value);
            ViewData["BranchName"] = $"{branchInfo.BranchCode} - {branchInfo.BranchName}";
            return View(model);

        }
        #endregion

        #region Record
        public ActionResult Record(Guid? Id)
        {
            //ViewData["IsView"] = Convert.ToString(TempData["IsView"]);
            var model = new CPCAnnexureIII();
            if (Id.HasValue)
            {
                model = annexureIIIRepo.GetById(Id.Value);
            }
            else
            {
                model.SrNo = annexureIIIRepo.GetNextSrNo();
                model.AnnexureIIIDate = DateTime.UtcNow;
                model.DateOfCashReturn = DateTime.Now;
            }
            //ViewBag.EmployeeList = new SelectList(employeeRepo.GetDropdown(), "Value", "Text");
            ViewBag.BrachList = new SelectList(branchRepo.GetDropdown(), "Value", "Text");
            //ViewBag.DenominationList = new SelectList(commonRepo.GetAllDenominationDropdown(), "Value", "Text");
            ViewBag.EmployeeList = new SelectList(employeeRepo.GetDropdown(), "Value", "Text");
            return View(model);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Record(CPCAnnexureIII model, List<CPCAnnexureIIIDetail> CPCAnnexureIIIDetail, string AnnexureIIIDate, string DateOfCashReturn)
        {
            try
            {
                if (model.Id.IsEmpty())
                {
                    model.CreatedBy = CurrentUser.Id;
                    model.CreatedOn = DateTime.Now;
                    model.AnnexureIIIDate = Utils.SetDateFormate(AnnexureIIIDate);
                    model.DateOfCashReturn = Utils.SetDateFormate(DateOfCashReturn);
                    model.Status = (int)AnnexureStatus.Inprocess;
                    model.IsActive = true;
                    model.Id = Guid.NewGuid();
                    var res = annexureIIIRepo.Create(model);
                    if (res.HasValue)
                    {
                        var lsToSave = CPCAnnexureIIIDetail.Where(x => x.UnfitSoiled > 0 && (x.FITReIssuable > 0 || x.UnfitSoiled > 0)).ToList();
                        lsToSave.ForEach(x => { x.Id = Guid.NewGuid(); x.AnnexureIIIId = model.Id; x.CreatedOn = DateTime.Now; x.CreatedBy = CurrentUser.Id; });
                        #region Save Details
                        if (lsToSave.Count > 0)
                        {
                            annexureIIIRepo.Create(lsToSave);
                        }
                        #endregion
                        model.Id = res.Value;
                    }

                    #region Activity Log
                    //appLog.Create(CurrentUser.OfficeId, model.Id, CurrentUser.Id, AppLogType.Activity, "CRM - Lead", model.FullName + " lead created", "~/CRM/Contact/LeadRecord > HttpPost", "<table class='table table-hover table-striped table-condensed' style='margin-bottom:15px;'><tr><th class='text-center'>Description</th></tr><tr><td><strong>" + model.FullName + "</strong> lead created by <strong>" + CurrentUser.FullName + "</strong>.</td></tr></table>");
                    #endregion

                    #region EmailSending

                    //Emailer.Send(model.Email, EmailTemplateType.ContactSignup, model);

                    //var appMessageModel = new AppMessage();
                    //appMessageModel.Email = model.Email;
                    //appMessageModel.Status = AppMessageStatus.Outbox;
                    //appMessageModel.Subject = EmailTemplateType.ContactSignup;
                    //appMessageModel.Message = EmailTemplateType.ContactSignup;
                    //TempData["SuccessMsg"] = "Message has been sent successfully.";
                    //realtime.UpdateMessages(null);
                    //appMessageModel.CreatorId = appMessageModel.ContactId = CurrentUser.Id;
                    //appMessageModel.Id = appMsg.Create(appMessageModel);

                    ////var cntact = appUser.GetUserById(new Guid(x));
                    //appMsg.Create(null, appMessageModel.Id, appMessageModel.CreatorId, null, AppMessageStatus.Inbox, EmailTemplateType.ContactSignup, model.Id, null);

                    //realtime.UpdateMessages(null);
                    #endregion

                    TempData["SuccessMsg"] = model.SrNo + " has been created successfully.";
                }
                else
                {
                    //model.UpdatedBy = CurrentUser.Id;
                    //model.UpdatedOn = DateTime.Now;
                    //bool res = annexureIIIRepo.Update(model);


                    //if (res)
                    //{
                    //    TempData["SuccessMsg"] = model.SrNo + " has been updated successfully.";
                    //}
                    //else
                    //{
                    //    TempData["ErrorMsg"] = "We have encountered an error while processing your request, Please see log for details.";
                    //}

                    #region Activity Log
                    //appLog.Create(CurrentUser.OfficeId, model.Id, CurrentUser.Id, AppLogType.Activity, "CRM - Lead", model.FullName + " lead updated", "~/CRM/Contact/LeadRecord > HttpPost", "<table class='table table-hover table-striped table-condensed' style='margin-bottom:15px;'><tr><th class='text-center'>Description</th></tr><tr><td><strong>" + model.FullName + "</strong> lead updated by <strong>" + CurrentUser.FullName + "</strong>.</td></tr></table>");
                    #endregion

                }
            }
            catch (Exception ex)
            {
                #region Error Log
                //appLog.Create(CurrentUser.OfficeId, null, CurrentUser.Id, AppLogType.Error, "CRM - Lead", ex.GetType().Name.ToSpacedTitleCase(), "~/CMS/FileManager/Index > HttpPost", "<table class='table table-hover table-striped'><tr><th class='text-right'>Source</th><td>" + ex.Source + "</td></tr><tr><th class='text-right'>URL</th><td>" + Request.Url.ToString() + "</td></tr><tr><th class='text-right'>Message</th><td>" + ex.Message + "</td></tr></table><table class='table table-hover table-striped table-condensed'><tr><th class='text-center'>Inner Exception</th></tr><tr><td>" + ex.InnerException + "</td></tr><tr><th class='text-center'>Stack Trace</th></tr><tr><td>" + ex.StackTrace.ToString() + "</td></tr></table>");
                #endregion

                TempData["ErrorMsg"] = "We have encountered an error while processing your request, Please see log for details.";
            }
            //if (SaveClick == "SaveAddNew")
            //{
            //    return RedirectToAction("Record");
            //}
            //else
            //{
            return RedirectToAction("AnnexureIIIs");
        }
        #endregion

        #region Remote Functions

        //[HttpPost]
        //public JsonResult GetCentersByRegionId(Guid Id)
        //{
        //    return Json("");//centerRepo.GetCentersDropdown(Id));
        //}
        //[HttpPost]
        //public JsonResult GetDesignationsByDepartId(Guid Id)
        //{
        //    return Json("");//designationRepo.GetDesignationDropdown(Id));
        //}
        #endregion

        #region Delete
        [HttpPost]
        public JsonResult Delete(Guid Id)
        {
            try
            {
                #region Activity Log
                //appLog.Create(CurrentUser.OfficeId, Id, CurrentUser.Id, AppLogType.Activity, "CRM", "Contact Deleted", "~/CRM/Contact/Delete > HttpPost", "<table class='table table-hover table-striped table-condensed' style='margin-bottom:15px;'><tr><th class='text-center'>Description</th></tr><tr><td>Contact deleted by <strong>" + CurrentUser.FullName + "</strong>.</td></tr></table>");
                #endregion
                annexureIIIRepo.InActiveRecord(Id);

                TempData["SuccessMsg"] = "AnnexureIII has been deleted successfully.";
            }
            catch (Exception ex)
            {
                #region Error Log

webapp/Areas/CPC/Views/AnnexureIII/AnnexureIIIs.cshtml
@{
    ViewBag.Title = "Cash Reconciliation";
}

<div class="user-Profile" style="min-height:430px;">
    <div id="employees-Container">
        @{ Html.RenderAction("_AllAnnexureIII", "AnnexureIII"); }
    </div>
</div>

@section scripts{
    <script>
        $(function () {
            filterDataTable("#AnnexureIII-dataTable", [1, 2, 3, 4, 5, 6, 7, 8], [0, 9], 10);
        });
    </script>
}

webapp/Areas/CPC/Views/AnnexureIII/_AllAnnexureIII.cshtml
@model List<CPCAnnexureIII>
@{var empList = ViewBag.Employees as List<CPCEmployee>; }

    <style>
        .menu-links a:hover {
            text-decoration: none;
        }
    </style>

    <div class="form-Modal">
        <div class="modal-content bg-transparent">
            <div class="modal-header">
                <h3 class="modal-title">
                    Cash Reconciliation Management
                    <span class="pull-right menu-links">
                        <a href="javascript://" class="text-muted" title="go to previous" style="margin:0 8px;" onclick="window.history.back()">
                            <i class="fa fa-angle-left"></i> <span class="grid-buttons"> Go Back</span>
                        </a>
                        @*<a href="javascript://" class="text-danger forceRedirect" title="delete record" style="margin:0 8px;" onclick="deleteMultipleRecords('@Url.Action("DeleteMultiple")', '.checkIt')">
                <i class="fa fa-trash"></i>
            </a>*@
                        <a href="@Url.Action("Record","AnnexureIII")" style="margin:0 8px;" title="add new">
                            <i class="fa fa-plus-circle text-primary"></i> <span class="grid-buttons"> Add New Cash Reconciliation</span>
                        </a>
                    </span>
                </h3>
            </div>
            @*<div class="row" style="margin:15px 0">
                <div class="col-md-12">
                    <ul class="nav nav-pills">
                        <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-hdd-o"></i> &nbsp; All</a></li>
                        <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-user"></i> &nbsp; Active</a></li>
                        <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-adjust"></i> &nbsp; Invited</a></li>
                        <li><a href="#" class="btn btn-default" style="padding:6px 20px;"> <i style="font-size:16px;" class="fa fa-user-times"></i> &nbsp; Suspended</a></li>
                    </ul>
                </div>
            </div>*@
            <div class="modal-body">
                <div class="table-responsive">
                    <table id="AnnexureIII-dataTable" class="table table-hover table-striped table-condensed">
                        <thead>
                            <tr>
                                <th><input type="checkbox" onchange="checkAll(this, 'checkIt');" /></th>
                                <th><input class="form-control input-sm input-tbl" type="text" placeholder="Sr No" id="AnnexureIII-dataTable_0" /></th>
                                <th><input class="form-control input-sm input-tbl" type="text" placeholder="Date" id="AnnexureIII-dataTable_1" /></th>
                                <th><input class="form-control input-sm input-tbl" type="text" placeholder="Branch" id="AnnexureIII-dataTable_2" /></th>
                                <th><input class="form-control input-sm input-tbl" type="text" placeholder="Bundles Collected" id="AnnexureIII-dataTable_3" /></th>
                                <th><input class="form-control input-sm input-tbl" type="text" placeholder="Cash Collected" id="AnnexureIII-dataTable_4" /></th>
                                <th><input class="form-control input-sm input-tbl" type="text" placeholder="Cash Reconciliation Date" id="AnnexureIII-dataTable_5" /></th>
                                <th><input class="form-control input-sm input-tbl" type="text" placeholder="Tota Cash Reconciliation" id="AnnexureIII-dataTable_6" /></th>
                                <th><input class="form-control input-sm input-tbl" type="text" placeholder="Status" id="AnnexureIII-dataTable_7" /></th>
                                <th class="text-center" width="100px">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var x in Model)
                            {
                            <tr>
                                <td>
                                    @if (CurrentUser.HasAnyPermission(BaseApp.Entity.AppPermission.All, BaseApp.Entity.AppPermission.CPC))
                                    {
                                        <input type="checkbox" class="checkIt" value="@x.Id" />
                                    }
                                </td>
                                <td><a href="@Url.Action("Details","AnnexureIII",new { Id = x.Id })">@x.SrNo</a></td>
                                <td>@x.AnnexureIIIDate.ToString(Constants.DATE_FORMAT_CLIENT_SIDE)</td>
                                <td>@($"{x.CPCProjectBranch.BranchCode} - {x.CPCProjectBranch.BranchName}")</td>
                                <td>@x.TotalBundlesCollected</td>
                                <td>@x.TotalCashCollected</td>
                                <td>@x.DateOfCashReturn.ToString(Constants.DATE_FORMAT_CLIENT_SIDE)</td>
                                <td>@x.TotalCashReturned</td>
                                <td>
                                    <label class="label label-warning">Inprocess</label>
                                    @*<label class="label label-success">@x.Status.ToSpacedTitleCase()</label>*@
                                </td>
                                <td class="text-center">
                                    <div class="btn-group btn-group-xs" role="group">
                                        <a href="@Url.Action("Details","AnnexureIII")/@x.Id" class="btn btn-primary" title="Details"><i class="fa fa-eye"></i></a>
                                        @if (CurrentUser.HasAnyPermission(BaseApp.Entity.AppPermission.All, BaseApp.Entity.AppPermission.CPC))
                                        {
                                            @*<a href="@Url.Action("Record","AnnexureIII")/@x.Id" class="btn btn-info" title="Edit"><i class="fa fa-edit"></i></a>*@
                                            <a href="javascript://" onclick="deleteRecord('@Url.Action("Delete")', '@x.Id')" class="btn btn-danger" title="Delete"><i class="fa fa-trash"></i></a>
                                        }
                                    </div>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer text-right">
                <div class="pull-right menu-links">
                    <a href="javascript://" class="text-muted" title="go to previous" style="margin:0 8px;" onclick="window.history.back()">
                        <i class="fa fa-angle-left fa-2x"></i> <span class="grid-buttons"> Go Back</span>
                    </a>
                    @*<a href="javascript://" class="text-danger forceRedirect" title="delete record" style="margin:0 8px;" onclick="deleteMultipleRecords('@Url.Action("DeleteMultiple")', '.checkIt')">
                        <i class="fa fa-trash fa-2x"></i>
                    </a>*@
                    <a href="@Url.Action("Record","AnnexureIII")" style="margin:0 8px;" title="add new">
                        <i class="fa fa-plus-circle fa-2x text-primary"></i> <span class="grid-buttons"> Add New Cash Reconciliation</span>
                    </a>
                </div>
            </div>
        </div>
    </div>